language: go

go:
        - 1.x

install:
        - go get github.com/cnf/structhash
        - go get github.com/golang/lint/golint
        - go get github.com/mattn/go-sqlite3
        - go get github.com/twpayne/go-gpx
        - go get github.com/urfave/cli
        - go get golang.org/x/net/context
        - go get golang.org/x/net/context/ctxhttp

sudo: false
